# Generated by Django 4.0.2 on 2022-08-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_web', '0003_instagramdownloaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramdownloaded',
            name='file',
            field=models.FileField(blank=True, upload_to='instagram_downloaded/'),
        ),
    ]
