# Generated by Django 4.0.2 on 2022-08-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_web', '0004_alter_instagramdownloaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramdownloaded',
            name='instagram_pk',
            field=models.CharField(max_length=30),
        ),
    ]
