# Generated by Django 4.0.2 on 2022-08-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_web', '0005_alter_instagramdownloaded_instagram_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramdownloaded',
            name='file',
            field=models.FileField(upload_to='instagram_downloaded/'),
        ),
    ]
