# Generated by Django 4.0.2 on 2022-08-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_web', '0006_alter_instagramdownloaded_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstagramDownloaded',
        ),
    ]
